aws:
  input_bucket: msia423-group11-spotifty-ready-to-rain
  input_key: ready_data.csv
  output_bucket: msia423-group11-spotify-artifacts
evaluate_performance:
  metrics:
  - R2
  - MSE
  - MAE
feature_engineer:
  OneHotEncoding:
  - genre
  - key
  - time_signature
  - mode
  columns_to_drop:
  - artist_name
  - track_name
  - track_id
  log_transform:
    log_duration: duration_ms
    log_instrumentalness: instrumentalness
    log_liviness: liveness
    log_loudness: loudness
    log_speechness: speechiness
    log_tempo: tempo
run_config:
  author: xwg9736
  name: Spotify-Popularity-Prediction
score_model:
  target_column: popularity
stremalit_inference:
  OneHotEncoding:
  - genre
  - key
  - time_sig
  - mode
  log_transform:
    log_duration: duration_ms
    log_instrumentalness: instrumentalness
    log_liviness: liveness
    log_loudness: loudness
    log_speechness: speechiness
    log_tempo: tempo
train_model:
  model:
    XGboost:
      learning_rate:
      - 0.1
      max_depth:
      - 5
      n_estimators:
      - 100
    neural_network:
      activation:
      - relu
      hidden_layer_sizes:
      - - 100
      max_iter:
      - 500
    random_forest:
      max_depth:
      - 15
      - 20
      max_features:
      - 35
      n_estimators:
      - 100
  target_column: popularity
  train_test_split:
    random_state: 123
    test_size: 0.2
